# Generated by Django 4.0.10 on 2024-03-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0002_twit_delete_twits'),
    ]

    operations = [
        migrations.AddField(
            model_name='twit',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
