# Generated by Django 5.0.3 on 2024-03-30 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0003_twit_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twit',
            name='date_of_birth',
        ),
    ]
