# Generated by Django 4.0.10 on 2024-04-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0007_alter_comment_author_alter_twit_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='twit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
