# Generated by Django 4.0.10 on 2024-04-15 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_private'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Private',
        ),
    ]
